# Generated by Django 2.1.3 on 2018-12-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
