# Generated by Django 2.1.3 on 2018-12-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0002_auto_20181202_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='OneToOne.Student'),
        ),
    ]
