# Generated by Django 2.1.3 on 2018-12-01 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20181129_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age', '-id']},
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='student',
            table='orm_student',
        ),
    ]
