# Generated by Django 2.1.3 on 2018-11-19 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='author',
            field=models.ForeignKey(on_delete=None, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
