# Generated by Django 2.1.3 on 2018-12-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
