# Generated by Django 2.1.3 on 2018-12-16 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='邮箱格式有误')]),
        ),
    ]
