# Generated by Django 2.1.3 on 2018-12-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonAggregate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookorder',
            table='book_order_other',
        ),
    ]
