# Generated by Django 2.1.3 on 2018-12-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonAggregate', '0002_auto_20181205_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookOrder',
            new_name='BookOrderSecond',
        ),
    ]
