# Generated by Django 2.1.3 on 2018-12-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonAggregate', '0003_auto_20181205_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookOrderSecond',
            new_name='BookOrder',
        ),
        migrations.AlterModelTable(
            name='bookorder',
            table='book_order',
        ),
    ]
