# Generated by Django 2.1.3 on 2018-12-05 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommonAggregate', '0004_auto_20181205_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
