# Generated by Django 2.1.3 on 2018-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0003_auto_20181202_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='news',
            field=models.ManyToManyField(related_name='tags', to='ManyToMany.New'),
        ),
    ]
