# Generated by Django 2.1.3 on 2018-12-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0004_auto_20181202_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='news',
            field=models.ManyToManyField(to='ManyToMany.New'),
        ),
    ]
