# Generated by Django 2.1.3 on 2018-12-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0005_auto_20181202_1807'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table='news',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
